Appliances/Components/NavigationMenuViewComponent.cs
using Appliances.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Appliances.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProduct repository;

        public NavigationMenuViewComponent(IProduct repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Appliances/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Appliances.Models;
using Appliances.ViewModel;
using System.Linq;

namespace Appliances.Controllers
{
    public class HomeController : Controller
    {
        private IProduct repository;
        public int PageSize = 12;
        public   HomeController(IProduct product)
        {
            repository = product;
        }

        public ViewResult Index(string Category,int ProductPage = 1) => View(new ProductListViewModel
        {
            Products = repository.Products
              .Where(p => Category == null || p.Category == Category)
              .OrderBy(p => p.Id)
              .Skip((ProductPage - 1) * PageSize)
              .Take(PageSize),
            PagingInfo = new PagingInfo {
                CurrentPage = ProductPage, ItemsPerPage = PageSize, 
                Totalitems = Category==null ? 
                repository.Products.Count(): 
                repository.Products.Where(e=>e.Category==Category).Count() 
            }
            ,CurrentCategory=Category
        });



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Appliances/Views/Home/Index.cshtml
@model ProductListViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <div class="container">
        <div class=" row">
            <div class="col-md-2">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-md-10">
@{ 
    int x = 1;

}
                
    
     
                    @foreach (var k in Model.Products)
                    {
                    if (x == 1) {
                        @Html.CreateList1();
                            };
    @await Html.PartialAsync("ProductSummary", k)
                        if (x == 3) {@Html.CreateList2();x = 0; }

                        x++;
                    }

</div>
        </div>
    </div>
</div>
<div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true" page-class="btn" page-class-normal="btn-secondary" page-class-selected="btn-primary" class="btn-group pull-right m-1"> </div>