Appliances/Components/CartSummaryViewComponent.cs
using Appliances.Models;
using Microsoft.AspNetCore.Mvc;

namespace Appliances.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Appliances/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Appliances.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Appliances.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProduct repository;

        public AdminController(IProduct repo)
        {
            repository = repo;

        }

        public ViewResult Index() => View(repository.Products);

        public ViewResult Edit(int Id) =>
            View(repository.Products
                .FirstOrDefault(p => p.Id == Id));

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = $"{product.Name} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
               
                return View(product);
            }
        }

        public ViewResult Create() => View("Edit", new Product());

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            Product deletedProduct = repository.DeleteProduct(Id);
            if (deletedProduct != null)
            {
                TempData["message"] = $"{deletedProduct.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

Appliances/Controllers/CartController.cs
using System.Linq;
using Appliances.Models;
using Appliances.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Appliances.Controllers
{
    public class CartController : Controller
    {
        private IProduct repository;
        private Cart cart;

        public CartController(IProduct repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int Id, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.Id == Id);
            if (product != null)
            {
                cart.AddItem(product, 1);
                
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int Id, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.Id == Id);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

Appliances/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Appliances.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Appliances.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult MarkShipped (int orderID)
        {
            Order order = repository.Orders.FirstOrDefault(o => o.OrderID == orderID);
            if (order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }
        [Authorize]
        public ViewResult List() => View(repository.Orders.Where(o => !o.Shipped));
    }
}

Appliances/Views/Shared/ProductSummary.cshtml
@model Product
@{
    ViewData["Title"] = "ProductSummary";
    Layout = null;
}


@*<div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="@Model.Image" width="125" height="300" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Model.Price</p>
                    <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden"  name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn-success">Add to Cart</button>
                    </form>

                </div>
            </div>
        </div>
    </div>*@


<div class="col-md-3 col-sm-6">
    <div class="product-grid2">
        <div class="product-image2">
            <a href="#">
                <img class="pic-1" style="width:160px; height:210px;" src="@Model.Image">
                <img class="pic-2"  style="width:160px; height:210px;"src="@Model.Image">

            </a>
            <ul class="social">
                <li><a href="#" data-tip="Quick View"><i class="fa fa-eye"></i></a></li>
                <li>
                    <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button href="#" type="submit" role="button" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></button>

                    </form>
                </li>
            </ul>
            <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button href="#" class="add-to-cart" type="submit" role="button" data-tip="Add to Cart">Add to cart</button>

            </form>
        </div>
        <div class="product-content">
            <h3 class="title"><a href="#">@Model.Name</a></h3>
            <span class="price">@Model.Price</span>
        </div>
    </div>
    </div>

Appliances/Views/Shared/_AdminMain.cshtml
@{
    ViewData["Title"] = "_AdminMain";
    Layout = null;
}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no" />


<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
</environment>
<script src="https://kit.fontawesome.com/04b2d2ca39.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="~/css/AdminLeftMenu.css" media="all" />


@*<div class="side">
    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
    <a class="nav-link" asp-controller="Admin" asp-action="Index">View products</a>
    <a class="nav-link" asp-controller="Order" asp-action="List">Orders</a>
    <a class="nav-link" asp-controller="Admin" asp-action="Create">New product</a>
</div>*@



<div class="sidebar-container">
    <div class="sidebar-logo">
       Appliances
    </div>
    <ul class="sidebar-navigation">
        <li class="header">Navigation</li>
        <li>
            <a asp-controller="Home" asp-action="Index">
                <i class="fas fa-home" aria-hidden="true"></i> Homepage
            </a>
        </li>
        <li>
            <a asp-controller="Admin" asp-action="Index">
                <i class="fas fa-database" aria-hidden="true"></i>  Products
            </a>
        </li>
        <li class="header"> Menu</li>
        <li>
            <a asp-controller="Order" asp-action="List">
                <i class="fas fa-users" aria-hidden="true"></i> Orders
            </a>
        </li>
        <li>
            <a asp-controller="Admin" asp-action="Create">
                <i class="fas fa-plus" aria-hidden="true"></i> New product
            </a>
        </li>
       
    </ul>
</div>





<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

Appliances/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no" />
    <title>@ViewData["Title"] - Appliances</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/signin.css" />
    <script src="https://kit.fontawesome.com/04b2d2ca39.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/ProductSummary.css"/>
    <link rel="stylesheet" asp-href-include="bower_components/Font-Awesome/css/all.min.css" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Appliances</a>
                <div class="collapse navbar-collapse id=" navbarSupportedContent"">
                    <ul class="navbar-nav mr-auto ">
                        <li class="nav-item active">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Other</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CartSummary")
                        </li>
                    </ul>
                </div>
                <form class="form-inline pull-xs-right">
                    <input class="form-control"  type="text" />
                    <button class=" btn btn-outline-success" type="submit">Search</button>
                </form>
                @if (!User.Identity.IsAuthenticated)
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                }
                else
                {
                    <a class="nav-link text-dark">Привет,@User.Identity.Name</a>
                    @if (User.IsInRole("admin")) {<a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a> }
                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Exit">Log out</a>

                }


            </nav>
        </div>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Appliances - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>